server:
  port: 80
spring:
  #thymeleaf热部署关闭缓存
  thymeleaf:
    cache: true
  #springboot 2.2.x 开启put delete等请求方式
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    username: root
    password: VuR0vpLo
    #mysql8版本以上的驱动包，需要指定以下时区
    url: jdbc:mysql://114.116.138.161:44066/uc_verification?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    #引入Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

